# To install homebrew:
# /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/services"
tap "homebrew/versions"
brew "git", link: false
brew "node"
brew "nvm"
brew "yarn"
brew "gpg-agent", link: true
brew "openssl"
brew "openssl@1.1"
brew "docker"
cask "kitematic"
brew "python"
cask "iterm2"
cask "atom"
cask "visual-studio-code"
cask "google-chrome"
cask "microsoft-office"
cask "docker"
cask "slack"
cask "java"
